### ISSUE TITLE
error: harmonic_mean requires at least one data point

### ISSUE THREAD

**Issue by asalahDyab** [chenyangh/SemEval2019Task3#10]
I faced issues when I tried to run get_metric function. the error in the following image. 
![issue1](https://user-images.githubusercontent.com/36843337/85218885-a2c9bc00-b3af-11ea-836a-2d410f979c08.PNG)

help please @chenyangh

**Comment by chenyangh** [comment]
HI @asalahDyab, thanks for posting it. You actually found a bug, and I am wondering why such an obvious bug is still there. I have fixed in this PR https://github.com/chenyangh/SemEval2019Task3/pull/12. You can pull from master again to get the fix. Thanks.

**Comment by asalahDyab** [comment]
> HI @asalahDyab, thanks for posting it. You actually found a bug, and I am wondering why such an obvious bug is still there. I have fixed in this PR #12. You can pull from master again to get the fix. Thanks.

Now its working. You effort is appreciated.
