### ISSUE TITLE
 RuntimeError: All input tensors must be on the same device. Received cuda:0 and cpu

### ISSUE THREAD

**Issue by asalahDyab** [chenyangh/SemEval2019Task3#11]
how to fix this error :
it happened when I tried to run one-fold function
![image](https://user-images.githubusercontent.com/36843337/85225281-133d0100-b3e1-11ea-921c-87035644282d.png)

**Comment by chenyangh** [comment]
OK, this error may be due to the evolving of pytorch API. you may try to change `x_len_sorted.cpu().numpy()` to `x_len_sorted` and see what happens.
This line: https://github.com/chenyangh/SemEval2019Task3/blob/c6204797b4b6cc08cb4d2d88108405f959d63ee9/model/hrlce.py#L110

**Comment by asalahDyab** [comment]
> OK, this error may be due to the evolving of pytorch API. you may try to change `x_len_sorted.cpu().numpy()` to `x_len_sorted` and see what happens.
> This line:
> 
> https://github.com/chenyangh/SemEval2019Task3/blob/c6204797b4b6cc08cb4d2d88108405f959d63ee9/model/hrlce.py#L110

Thank you for response. 
I tried it but still same error. 
I think the error in this statement emb_x = torch.cat((emb_x, elmo_x), dim=2)

![image](https://user-images.githubusercontent.com/36843337/85279227-201c2c00-b497-11ea-82bd-f49609d31a56.png)

**Comment by chenyangh** [comment]
The error msg says that cuda and cpu not matched. Since the error shows that the code that causes the error is still `x_len_sorted.cpu().numpy()`. Can you double-check that the change has been made?

**Comment by asalahDyab** [comment]
> The error msg says that cuda and cpu not matched. Since the error shows that the code that causes the error is still `x_len_sorted.cpu().numpy()`. Can you double-check that the change has been made?

I tried many times but still same error. Any suggestion please

**Comment by chenyangh** [comment]
@asalahDyab Hi, I think you are right about the `emb_x = torch.cat((emb_x, elmo_x), dim=2)`, maybe you can try to change it to `emb_x = torch.cat((emb_x, elmo_x.cuda()), dim=2)`. What I don't understand is why L110 is not changed in the error msg. You should try to transfer ELMo embedding to GPU first. Sorry I did not see that arrow which points to L108.

**Comment by asalahDyab** [comment]
> @asalahDyab Hi, I think you are right about the `emb_x = torch.cat((emb_x, elmo_x), dim=2)`, maybe you can try to change it to `emb_x = torch.cat((emb_x, elmo_x.cuda()), dim=2)`. What I don't understand is why L110 is not changed in the error msg. You should try to transfer ELMo embedding to GPU first. Sorry I did not see that arrow which points to L108.

yes its solved thanks for your support . but it follows by this error. do you have any idea? 
![image](https://user-images.githubusercontent.com/36843337/85818480-cf9c1b80-b781-11ea-8b45-846b221e9a9b.png)

**Comment by chenyangh** [comment]
I remember this is related to the Pytorch version. You might need to install pytorch 1.0.1

**Comment by asalahDyab** [comment]
> I remember this is related to the Pytorch version. You might need to install pytorch 1.0.1

I have installed  pytorch 1.0.1 but it cause a lot of other errors. like that needs to start from the beginning. 
your efforts is appropriated.
