### ISSUE TITLE
error: update gpu driver or nvidia driver is too old on colab

### ISSUE THREAD

**Issue by asalahDyab** [chenyangh/SemEval2019Task3#13]
I installed version 1.0.0 of PyTourch. this error appear in colab. Do you have an idea? 
![image](https://user-images.githubusercontent.com/36843337/86219882-dec10600-bb93-11ea-8831-df3dd5f15299.png)

**Comment by chenyangh** [comment]
Hi, sorry I don't really use the colab, I am not sure how did you install pytorch on it. I am sure pytorch1.0.1 does not need cuda > 10.1. 
Here is what I would install it if I have conda environment:
`conda install pytorch==1.0.1 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch`
Also, pytorch 1.0.0 is not the same as 1.0.1, in fact, I remember they are quite different. 

Back to the bug you have which leads to this situation. It is actually coming from the deepmoji implementation by hugginface. I just checked that someone has a PR that could have potentially made it support pytorch > 1.2. 
https://github.com/huggingface/torchMoji/pull/28 Maybe you can install that version to make your code working. I know this is painful, but unfortunately, I currently do not have time to fix the version issue myself. I may try to merge that PR in near future.
