### ISSUE TITLE
pytorch_model.bin not exist

### ISSUE THREAD

**Issue by asalahDyab** [chenyangh/SemEval2019Task3#9]
when I run trainer_hrlce.py ,this error appear. guide me please
ValueError: ERROR (load_weights): The weights file at /content/SemEval2019Task3/model/pytorch_model.bin does not exist

**Comment by chenyangh** [comment]
Hi, I don't quite understand this error. Do you main paste the full error msg?
On the other hand, have you followed the instructions and installed the `TorchMoji` module and downloaded the weights?

**Comment by chenyangh** [comment]
OK, I went to check and confirmed that `pytorch_model.bin` is the pre-trained model for TorchMoji. So you should install it first.

**Comment by asalahDyab** [comment]
> OK, I went to check and confirmed that `pytorch_model.bin` is the pre-trained model for TorchMoji. So you should install it first.

yes, its work with me now, thanks a lot for your help. but also I faced issues when I tried to run get_metric function. the error in the following image. 
![issue1](https://user-images.githubusercontent.com/36843337/85218729-0ce16180-b3ae-11ea-9827-14d6f2cb963f.PNG)

**Comment by asalahDyab** [comment]
thanks alot for your help. its working with me now
